branch-defaults:
  master:
    environment: staging
global:
  application_name: nsw-procurement-hub
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.5 (Puma)
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
